### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by kbaum** [tristandunn/pusher-fake#19]
Any way to get pusher-fake to work from ssl pages?  I have tried it and the browser cannot communicate with a non-ssl url.

thx

**Comment by edwardotis** [comment]
Hi @tristandunn ,

Thanks for putting together this project. 

 Regarding this closed bug labeled, 'Support for SSL'.
I looked at your changes, and in no way do they support configuration for SSL on the underlying Thin server. This bug should be left open to let people know SSL is not supported by the project. There is no way to configure SSL in the pusher-fake-example through the exposed configuration options of pusher-fake.

Incidentally, I'm here because my pusher js client is instantiated with 'encrypted: false' and             'enabledTransports: ["ws"]', but it keeps throwing the following ssl errors in a row and then failing to connect to the pusher fake example Thin/EventMachine server: 

[15704:15743:0312/072344:ERROR:ssl_client_socket_openssl.cc(1149)] handshake failed; returned -1, SSL error code 1, net_error -100                     
[15704:15743:0312/072344:ERROR:ssl_client_socket_openssl.cc(1149)] handshake failed; returned -1, SSL error code 1, net_error -100                     
[15704:15743:0312/072344:ERROR:ssl_client_socket_openssl.cc(1149)] handshake failed; returned -1, SSL error code 1, net_error -100                     
[15704:15704:0312/072344:INFO:CONSOLE(2378)] "WebSocket connection to 'ws://localhost:50389/app/<hidden>?protocol=7&client=js&version=3.0. 
0&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED", source: chrome-extension://<hidden>/pusher-js.js (2378)

**Comment by tristandunn** [comment]
First, I'm confused as to why it's trying to use SSL when `encrypted` is set to false.

Second, the WebSocket server [receives all `socket_options`](https://github.com/tristandunn/pusher-fake/blob/master/lib/pusher-fake/server.rb#L18) and the Thin server is [passed other options at creation](https://github.com/tristandunn/pusher-fake/blob/master/lib/pusher-fake/server.rb#L39-L41). So you can [create a secure WebSocket server](https://github.com/igrigorik/em-websocket#secure-server) and [provide Thin SSL options](https://github.com/macournoyer/thin/blob/0770aa00399480bbd8ca7391d416c8700818e719/lib/thin/backends/base.rb#L37-L39) if you wish. I don't support it by default because it would likely create more support issues. And the library is meant for development and testing, which I don't think necessarily requires SSL.

That being said I'll reopen this issue for me to add these details to the README for people who wish to run it with SSL.

**Comment by tristandunn** [comment]
Added the details in 8b6f8e4f5a5160909861502df83c8e9a69d24a22.

**Comment by edwardotis** [comment]
Thanks, Tristan. 
I'm coming from a java and python background, so configuring options in a ruby/rails environment is new to me. This additional documentation helps.

For completeness, here's a link to the issue where I got to the bottom of my ssl_client_socket_openssl.cc bug. It had nothing to do with any problems in pusher-fake. 

https://github.com/tristandunn/pusher-fake-example/issues/3
