### ISSUE TITLE
not sure what I am doing wrong

### ISSUE THREAD

**Issue by PatrickArthur** [tristandunn/pusher-fake#47]
I install the gem, I am creating the new pusher instant in a javascript file and include this in the top of my application html

`
- content_for :javascript_includes do
      = javascript_include_tag 'application'
  :javascript
- if defined?(PusherFake)
  var instance = "#{PusherFake.javascript}"
- else
  var instance = new Pusher("#{Pusher.key}", { encrypted: true });
  TS.application.init_push_notices(instance, "#{current_user.id}");
  `

when I run my tests I get an error saying 

Warning: `Pusher.app_id` is not set. Should be set before including PusherFake.
Warning: `Pusher.key` is not set. Should be set before including PusherFake.
Warning: `Pusher.secret` is not set. Should be set before including PusherFake

**Comment by PatrickArthur** [comment]
I did that in my config/initializer/pusher.rb file and it still gives me the issue, the test I am running runs a class that runs a mailer and pusher.trigger...seems to error out always saying the app-key isn't defined.

**Comment by tristandunn** [comment]
You must be initializing the fake before the configuration then, since the [warnings aren't show until it's included](https://github.com/tristandunn/pusher-fake/blob/2c15a159e02112a6851fe808885cec16d0c963d4/lib/pusher-fake/support/base.rb#L1-L6). Perhaps add some logging yourself to see the loading order and adjust it.
