### ISSUE TITLE
Docker Compose and multiple services

### ISSUE THREAD

**Issue by dukedave** [tristandunn/pusher-fake#49]
It would be nice if we could run the `PusherFake::Server` as a separate service in [Docker Compose](https://docs.docker.com/compose/), such that other services in the defined in the compose file could be linked to it.

In our use case we have a `web` service and a `sidekiq` service.
Unfortunately if we simply follow the README then messages published on `sidekiq`  will not be published to the browser (via `web`) because each service has its own `PusherFake::Server`.

**Comment by tristandunn** [comment]
As it mentions, you'll only want to run the fake for a single process. So you'll need to decided where to run it and adjust accordingly. And since you need to share the single server between multiple services, you should be able to set the `host` and `port` options for both fake servers in the configuration via the [`socket_options` and `web_options`](https://github.com/tristandunn/pusher-fake/blob/4dd8facc26020b545ca90320e4651a66a8c04b38/lib/pusher-fake/configuration.rb#L45-L46).

1. Start the the fake server on a single service, via an environment variable or something else.
2. Set the `port`, and possibly `host`, for the fake to be the same between services, perhaps also using shared environment variables or variables provided by Docker.
3. If you'd like to *only* run the fake by itself, you could write a separate small application or a simple script to only run it, which would then be it's own service in Docker.

Perhaps adding a binary would better assist the ability to run it as a shared service.

**Comment by dukedave** [comment]
Excellent, well I went with option 3, and I ended up with something [like this](https://gist.github.com/dukedave/7accfdf33a7403687be6d719d1073026).
So my `pusher-fake.rb` is probably a workaround for the binary you were thinking of?

After adding `pusher` to the `links` for both `web` and `sidekiq` I could get the former to publish, but the latter did not :disappointed: 
I will play around a little more and report back.

**Comment by tristandunn** [comment]
Yeah, that's pretty close to the binary I imagined.

Double check that the host and port matches in both services. Maybe I should output that to the log when starting.

**Comment by tristandunn** [comment]
Started on adding a binary in the [td-binary](https://github.com/tristandunn/pusher-fake/compare/td-binary) branch.

Any luck on communication between the two services?

**Comment by dukedave** [comment]
Oh wow, thanks for jumping on that so quickly!
With my gist:

1. I was able to have the browser connect (i.e. I saw the `UPGRADE` to websocket in dev tools), but:
1. When I published a message from another service (`sidekiq`) it didn't appear get back to the browser.

I'll try and find time to look again some time this week.

**Comment by tristandunn** [comment]
Finally got around to merging the binary in https://github.com/tristandunn/pusher-fake/commit/63d388f330b64ca43c5909c6bee3c2cf13f33b17. I'll probably release a new version today as well.

Any update on your setup?

**Comment by dukedave** [comment]
Nice! Thanks!
Not working on it right now, but next time I'm in that code I'll be sure to report back.

**Comment by tristandunn** [comment]
Ok. I just released [v1.8.0](https://rubygems.org/gems/pusher-fake/versions/1.8.0). I'm going to close this, but feel free to reopen if you encounter issues when you return to the code.

**Comment by naw** [comment]
I am running pusher-fake inside a Rails web service using docker compose.

At first I had trouble getting the browser (on the host) to access the pusher-fake websocket server.

Here is what finally worked for me:

1. specify a specific port number in PusherFake socket_options configuration.
2. in docker-compose.yml, ensure this specific port is shared to the host.
3. specify '0.0.0.0' as the host in the PusherFake socket_options configuration because traffic from the host to the container will _not_ come through on the container's '127.0.0.1'.
4. configure the client (browser) to use host `127.0.0.1`, not '0.0.0.0'.

The crux of the issue (for me) was configuring PusherFake to listen on `0.0.0.0` while simultaneously configuring Pusher in the client to use `127.0.0.1` as the `wsHost`. For me, configuring the websocket to listen on `0.0.0.0` was also making the client use `0.0.0.0`.

Just posting in case this helps someone else in the same boat.
